---

# Contributed extensions

- name: PostgreSQL | Install PostgreSQL contrib
  apt: 
    name: "postgresql-contrib-{{ postgresql_version }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | d(3600) }}"
  notify: restart postgresql