---

# Development headers and libraries

- name: PostgreSQL | Install development headers
  apt:
    name: libpq-dev
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | d(3600) }}"
  notify: restart postgresql