---

# PostGIS

- name: PostgreSQL | Install PostGIS extensions
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | d(3600) }}"
  with_items:
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_postgis_version }}"
    - libgeos-c1
  notify: restart postgresql