---

- name: PostgreSQL | Ensure PostgreSQL databases are present
  postgresql_db:
    name: "{{ item.name }}"
    lc_collate: "{{ item.lc_collate | d(postgresql_locale) }}"
    lc_ctype: "{{ item.lc_ctype | d(postgresql_ctype) }}"
    encoding: "{{ item.encoding | d(postgresql_encoding) }}"
    template: "{{ item.template | d('template0') }}"
    login_host: "{{ item.login_host | d('localhost') }}"
    login_password: "{{ item.login_password | d(omit) }}"
    login_user: "{{ item.login_user | d(postgresql_admin_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | d(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | d(omit) }}"
    owner: "{{ item.owner | d(postgresql_admin_user) }}"
    state: "{{ item.state | d('present') }}"
  with_items: "{{ postgresql_databases }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars: 
    ansible_ssh_pipelining: true 
