---

- name: Ensure PostgreSQL data directory exists
  become: yes
  file: 
    path: "{{ postgresql_data_directory }}"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_group }}"
    state: directory
    mode: 0700
  register: pgdata_dir_exists

- name: Ensure the locale for lc_collate and lc_ctype is generated
  become: yes
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ postgresql_locale }}"
    - "{{ postgresql_ctype }}"

- name: Check if PostgreSQL is initialized
  become: yes
  stat:
    path: "{{ postgresql_data_directory }}/PG_VERSION"
  register: pgdata_dir_version

- name: Recreate cluster - drop existing
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  shell: pg_dropcluster --stop {{ postgresql_version }} {{ postgresql_cluster_name }}
  when: postgresql_cluster_reset and pgdata_dir_exists.changed  

- name: Recreate cluster - start new (with specified locale)
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  shell: pg_createcluster --start --locale {{ postgresql_locale }} {{ postgresql_version }} {{ postgresql_cluster_name }}
  when: postgresql_cluster_reset and pgdata_dir_exists.changed 