---

- name: Add PostgreSQL repository apt-key
  become: yes
  apt_key:
    id: "{{ postgresql_apt_key_id }}"
    url: "{{ postgresql_apt_key_url }}"
    state: present
  when: postgresql_apt_key_id and postgresql_apt_key_url

- name: Add PostgreSQL repository
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present
  when: postgresql_apt_repository | default('') != ''

- name: Install PostgreSQL dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | d(3600) }}"
  with_items: "{{ postgresql_dependencies }}"

- name: Install PostgreSQL
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
    default_release: "{{ postgresql_default_release | d(ansible_distribution_release + '-pgdg') }}"
    cache_valid_time: "{{ apt_cache_valid_time | d(3600) }}"
  environment: "{{ postgresql_env }}"
  with_items:
    - "postgresql-{{ postgresql_version }}"
    - "postgresql-client-{{ postgresql_version }}"