---

- import_tasks: install.yml
  tags:
    - postgresql
    - postgresql_install

- import_tasks: initialize.yml
  tags:
    - postgresql
    - postgresql_initialize

- import_tasks: cluster.yml
  tags:
    - postgresql
    - postgresql_cluster
  
- import_tasks: extensions.yml
  tags:
    - postgresql
    - postgresql_extensions

- import_tasks: configure.yml
  tags:
    - postgresql
    - postgresql_configure

- name: PostgreSQL | Ensure PostgreSQL is started and enabled on boot
  service:
    name: postgresql
    state: started
    enabled: yes
    
- import_tasks: databases.yml
  tags:
    - postgresql
    - postgresql_databases

- import_tasks: users.yml
  tags:
    - postgresql
    - postgresql_users