---

- include_tasks: install.yml

- include_tasks: initialize.yml

- include_tasks: cluster.yml

- include_tasks: extensions.yml

- include_tasks: configure.yml

- name: PostgreSQL | Ensure PostgreSQL is started and enabled on boot
  service:
    name: postgresql
    state: started
    enabled: yes
    
- include_tasks: databases.yml

- include_tasks: users.yml