---

- include_tasks: install.yml

- include_tasks: initialize.yml

- include_tasks: cluster.yml

- include_tasks: extensions.yml

- include_tasks: configure.yml

- include_tasks: databases.yml

- include_tasks: users.yml