---

- name: PostgreSQL | Ensure the PostgreSQL users are present
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | d(omit) }}"
    priv: "{{ item.priv | d(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | d(omit) }}"
    db: "{{ item.db | d(omit) }}"
    login_host: "{{ item.login_host | d('localhost') }}"
    login_password: "{{ item.login_password | d(omit) }}"
    login_user: "{{ item.login_user | d(postgresql_admin_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | d(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | d(omit) }}"
    state: "{{ item.state | d('present') }}"
  with_items: "{{ postgresql_users }}"
  # no_log: true
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true