---

- name: reload postgresql
  become: yes
  command: pg_ctlcluster {{ postgresql_version }} {{ postgresql_cluster_name }} reload

- name: restart postgresql
  become: yes
  command: pg_ctlcluster {{ postgresql_version }} {{ postgresql_cluster_name }} restart